from typing import Dict, NamedTuple, Set, Optional, List
from ..oot.ntype import int32


class FF1PRLocationData(NamedTuple):
    region: str
    type: str
    flag: int32
    # er_region: str  # entrance rando region

location_base_id = 398735498

location_table: Dict[str, FF1PRLocationData] = {
    "Chaos Shrine - Unlocked Single": FF1PRLocationData("Pravoka Region", "Treasure", 5),
    "Chaos Shrine - Unlocked Duo 1": FF1PRLocationData("Pravoka Region", "Treasure", 6),
    "Chaos Shrine - Unlocked Duo 2": FF1PRLocationData("Pravoka Region", "Treasure", 7),
    "Chaos Shrine - Locked Single": FF1PRLocationData("Pravoka Region", "Treasure", 10),
    "Chaos Shrine - Locked Duo 1": FF1PRLocationData("Pravoka Region", "Treasure", 8),
    "Chaos Shrine - Locked Duo 2": FF1PRLocationData("Pravoka Region", "Treasure", 9),
    "Castle Cornelia - Princess": FF1PRLocationData("Pravoka Region", "GameObject", 400),
    "Castle Cornelia - Treasury 1": FF1PRLocationData("Pravoka Region", "Treasure", 0),
    "Castle Cornelia - Treasury 2": FF1PRLocationData("Pravoka Region", "Treasure", 1),
    "Castle Cornelia - Treasury 3": FF1PRLocationData("Pravoka Region", "Treasure", 2),
    "Castle Cornelia - Treasury 4": FF1PRLocationData("Pravoka Region", "Treasure", 3),
    "Castle Cornelia - Treasury 5": FF1PRLocationData("Pravoka Region", "Treasure", 4),
    "Castle Cornelia - Treasury Major": FF1PRLocationData("Pravoka Region", "Treasure", 505),
    "Matoya's Cave - Chest 1": FF1PRLocationData("Pravoka Region", "Treasure", 11),
    "Matoya's Cave - Chest 2": FF1PRLocationData("Pravoka Region", "Treasure", 12),
    "Matoya's Cave - Chest 3": FF1PRLocationData("Pravoka Region", "Treasure", 13),
    "Matoya's Cave - Matoya": FF1PRLocationData("Pravoka Region", "GameObject", 247),
    "Pravoka - Bikke": FF1PRLocationData("Pravoka Region", "GameObject", 401),
    "Marsh Cave B2 (Top) - Single": FF1PRLocationData("Innersea Region", "Treasure", 24),
    "Marsh Cave B2 (Top) - Corner": FF1PRLocationData("Innersea Region", "Treasure", 232),
    "Marsh Cave B2 (Top) - Duo 1": FF1PRLocationData("Innersea Region", "Treasure", 21),
    "Marsh Cave B2 (Top) - Duo 2": FF1PRLocationData("Innersea Region", "Treasure", 22),
    "Marsh Cave B2 (Bottom) - Leftmost Chest": FF1PRLocationData("Innersea Region", "Treasure", 231),
    "Marsh Cave B2 (Bottom) - Center Chest": FF1PRLocationData("Innersea Region", "Treasure", 23),
    "Marsh Cave B2 (Bottom) - Rightmost Chest": FF1PRLocationData("Innersea Region", "Treasure", 233),
    "Marsh Cave B3 (Bottom) - Distant Chest": FF1PRLocationData("Innersea Region", "Treasure", 25),
    "Marsh Cave B3 (Bottom) - Tetris-Z First": FF1PRLocationData("Innersea Region", "Treasure", 26),
    "Marsh Cave B3 (Bottom) - Tetris-Z Middle 1": FF1PRLocationData("Innersea Region", "Treasure", 27),
    "Marsh Cave B3 (Bottom) - Tetris-Z Middle 2": FF1PRLocationData("Innersea Region", "Treasure", 234),
    "Marsh Cave B3 (Bottom) - Tetris-Z Major": FF1PRLocationData("Innersea Region", "Treasure", 501),
    "Marsh Cave B3 (Bottom) - Tetris-Z Last": FF1PRLocationData("Innersea Region", "Treasure", 28),
    "Marsh Cave B3 (Bottom) - First Room Chest": FF1PRLocationData("Innersea Region", "Treasure", 29),
    "Marsh Cave B3 (Bottom) - Dunno Chest": FF1PRLocationData("Innersea Region", "Treasure", 235),
    "Marsh Cave B3 (Bottom) - Locked Corner": FF1PRLocationData("Innersea Region", "Treasure", 30),
    "Marsh Cave B3 (Bottom) - Locked Middle": FF1PRLocationData("Innersea Region", "Treasure", 31),
    "Marsh Cave B3 (Bottom) - Locked Cross": FF1PRLocationData("Innersea Region", "Treasure", 32),
    "Western Keep - Astos": FF1PRLocationData("Innersea Region", "GameObject", 246),
    "Western Keep - Treasury 1": FF1PRLocationData("Innersea Region", "Treasure", 18),
    "Western Keep - Treasury 2": FF1PRLocationData("Innersea Region", "Treasure", 19),
    "Western Keep - Treasury 3": FF1PRLocationData("Innersea Region", "Treasure", 20),
    "Elven Castle - Elf Prince": FF1PRLocationData("Innersea Region", "GameObject", 248),
    "Elven Castle - Treasury 1": FF1PRLocationData("Innersea Region", "Treasure", 14),
    "Elven Castle - Treasury 2": FF1PRLocationData("Innersea Region", "Treasure", 15),
    "Elven Castle - Treasury 3": FF1PRLocationData("Innersea Region", "Treasure", 16),
    "Elven Castle - Treasury 4": FF1PRLocationData("Innersea Region", "Treasure", 17),
    "Mount Duergar - Entrance 1": FF1PRLocationData("Innersea Region", "Treasure", 33),
    "Mount Duergar - Entrance 2": FF1PRLocationData("Innersea Region", "Treasure", 34),
    "Mount Duergar - Treasury 1": FF1PRLocationData("Innersea Region", "Treasure", 35),
    "Mount Duergar - Treasury 2": FF1PRLocationData("Innersea Region", "Treasure", 36),
    "Mount Duergar - Treasury 3": FF1PRLocationData("Innersea Region", "Treasure", 37),
    "Mount Duergar - Treasury 4": FF1PRLocationData("Innersea Region", "Treasure", 38),
    "Mount Duergar - Treasury 5": FF1PRLocationData("Innersea Region", "Treasure", 39),
    "Mount Duergar - Treasury 6": FF1PRLocationData("Innersea Region", "Treasure", 40),
    "Mount Duergar - Treasury 7": FF1PRLocationData("Innersea Region", "Treasure", 41),
    "Mount Duergar - Treasury 8": FF1PRLocationData("Innersea Region", "Treasure", 42),
    "Mount Duergar - Smitt": FF1PRLocationData("Innersea Region", "GameObject", 405),
    "Cavern of Earth B1 - Single": FF1PRLocationData("Melmond Region", "Treasure", 43),
    "Cavern of Earth B1 - Appendix 1": FF1PRLocationData("Melmond Region", "Treasure", 44),
    "Cavern of Earth B1 - Appendix 2": FF1PRLocationData("Melmond Region", "Treasure", 45),
    "Cavern of Earth B1 - Side Path 1": FF1PRLocationData("Melmond Region", "Treasure", 46),
    "Cavern of Earth B1 - Side Path 2": FF1PRLocationData("Melmond Region", "Treasure", 47),
    "Cavern of Earth B2 - Guarded 1": FF1PRLocationData("Melmond Region", "Treasure", 48),
    "Cavern of Earth B2 - Guarded 2": FF1PRLocationData("Melmond Region", "Treasure", 49),
    "Cavern of Earth B2 - Guarded 3": FF1PRLocationData("Melmond Region", "Treasure", 50),
    "Cavern of Earth B2 - Side Room 1": FF1PRLocationData("Melmond Region", "Treasure", 51),
    "Cavern of Earth B2 - Side Room 2": FF1PRLocationData("Melmond Region", "Treasure", 52),
    "Cavern of Earth B2 - Side Room 3": FF1PRLocationData("Melmond Region", "Treasure", 53),
    "Cavern of Earth B3 - Side Room": FF1PRLocationData("Melmond Region", "Treasure", 54),
    "Cavern of Earth B3 - TFC": FF1PRLocationData("Melmond Region", "Treasure", 55),
    "Cavern of Earth B3 - Asher Trunk": FF1PRLocationData("Melmond Region", "Treasure", 56),
    "Cavern of Earth B3 - Vampire's Closet": FF1PRLocationData("Melmond Region", "Treasure", 57),
    "Cavern of Earth B3 - Vampire's Chest": FF1PRLocationData("Melmond Region", "Treasure", 508),
    "Cavern of Earth B4 - Armory 1": FF1PRLocationData("Cavern of Earth Deep", "Treasure", 58),
    "Cavern of Earth B4 - Armory 2": FF1PRLocationData("Cavern of Earth Deep", "Treasure", 59),
    "Cavern of Earth B4 - Armory 3": FF1PRLocationData("Cavern of Earth Deep", "Treasure", 60),
    "Cavern of Earth B4 - Armory 4": FF1PRLocationData("Cavern of Earth Deep", "Treasure", 61),
    "Cavern of Earth B4 - Armory 5": FF1PRLocationData("Cavern of Earth Deep", "Treasure", 62),
    "Cavern of Earth B4 - Lich's Closet 1": FF1PRLocationData("Cavern of Earth Deep", "Treasure", 63),
    "Cavern of Earth B4 - Lich's Closet 2": FF1PRLocationData("Cavern of Earth Deep", "Treasure", 64),
    "Cavern of Earth B4 - Lich's Closet 3": FF1PRLocationData("Cavern of Earth Deep", "Treasure", 65),
    "Giant's Cave - Chest 1": FF1PRLocationData("Melmond Region", "Treasure", 241),
    "Giant's Cave - Chest 2": FF1PRLocationData("Melmond Region", "Treasure", 242),
    "Giant's Cave - Chest 3": FF1PRLocationData("Melmond Region", "Treasure", 243),
    "Giant's Cave - Chest 4": FF1PRLocationData("Melmond Region", "Treasure", 244),
    "Sage's Cave - Sarda": FF1PRLocationData("Sage Region", "GameObject", 253),
    "Crescent Lake - Canoe Sage": FF1PRLocationData("Crescent Region", "GameObject", 402),
    "Mount Gulg B2 - Guarded": FF1PRLocationData("Gulg Region", "Treasure", 66),
    "Mount Gulg B2 - Center": FF1PRLocationData("Gulg Region", "Treasure", 67),
    "Mount Gulg B2 - Hairpins": FF1PRLocationData("Gulg Region", "Treasure", 68),
    "Mount Gulg B2 - Shortpins": FF1PRLocationData("Gulg Region", "Treasure", 69),
    "Mount Gulg B2 - Vertpins 1": FF1PRLocationData("Gulg Region", "Treasure", 70),
    "Mount Gulg B2 - Vertpins 2": FF1PRLocationData("Gulg Region", "Treasure", 71),
    "Mount Gulg B2 - Armory 1": FF1PRLocationData("Gulg Region", "Treasure", 72),
    "Mount Gulg B2 - Armory 2": FF1PRLocationData("Gulg Region", "Treasure", 73),
    "Mount Gulg B2 - Armory 3": FF1PRLocationData("Gulg Region", "Treasure", 74),
    "Mount Gulg B2 - Armory 4": FF1PRLocationData("Gulg Region", "Treasure", 75),
    "Mount Gulg B2 - Armory 5": FF1PRLocationData("Gulg Region", "Treasure", 76),
    "Mount Gulg B2 - Armory 6": FF1PRLocationData("Gulg Region", "Treasure", 77),
    "Mount Gulg B2 - Armory 7": FF1PRLocationData("Gulg Region", "Treasure", 78),
    "Mount Gulg B2 - Armory 8": FF1PRLocationData("Gulg Region", "Treasure", 79),
    "Mount Gulg B2 - Armory 9": FF1PRLocationData("Gulg Region", "Treasure", 80),
    "Mount Gulg B2 - Armory 10": FF1PRLocationData("Gulg Region", "Treasure", 81),
    "Mount Gulg B2 - Armory 11": FF1PRLocationData("Gulg Region", "Treasure", 82),
    "Mount Gulg B2 - Armory 12": FF1PRLocationData("Gulg Region", "Treasure", 83),
    "Mount Gulg B4 - Entrance 1": FF1PRLocationData("Gulg Region", "Treasure", 84),
    "Mount Gulg B4 - Entrance 2": FF1PRLocationData("Gulg Region", "Treasure", 85),
    "Mount Gulg B4 - First Greed": FF1PRLocationData("Gulg Region", "Treasure", 86),
    "Mount Gulg B4 - Worm Room 1": FF1PRLocationData("Gulg Region", "Treasure", 87),
    "Mount Gulg B4 - Worm Room 2": FF1PRLocationData("Gulg Region", "Treasure", 88),
    "Mount Gulg B4 - Worm Room 3": FF1PRLocationData("Gulg Region", "Treasure", 89),
    "Mount Gulg B4 - Worm Room 4": FF1PRLocationData("Gulg Region", "Treasure", 90),
    "Mount Gulg B4 - Worm Room 5": FF1PRLocationData("Gulg Region", "Treasure", 91),
    "Mount Gulg B4 - Second Greed 1": FF1PRLocationData("Gulg Region", "Treasure", 92),
    "Mount Gulg B4 - Second Greed 2": FF1PRLocationData("Gulg Region", "Treasure", 93),
    "Mount Gulg B4 - Side Room 1": FF1PRLocationData("Gulg Region", "Treasure", 94),
    "Mount Gulg B4 - Side Room 2": FF1PRLocationData("Gulg Region", "Treasure", 95),
    "Mount Gulg B4 - Side Room 3": FF1PRLocationData("Gulg Region", "Treasure", 236),
    "Mount Gulg B4 - Last Room 1": FF1PRLocationData("Gulg Region", "Treasure", 96),
    "Mount Gulg B4 - Last Room 2": FF1PRLocationData("Gulg Region", "Treasure", 97),
    "Mount Gulg B5 - West Room": FF1PRLocationData("Gulg Region", "Treasure", 98),
    "Mount Gulg B5 - Northeast Room": FF1PRLocationData("Gulg Region", "Treasure", 237),
    "Mount Gulg B5 - East Room": FF1PRLocationData("Gulg Region", "Treasure", 238),
    "Mount Gulg B5 - Southeast Room": FF1PRLocationData("Gulg Region", "Treasure", 239),
    "Cavern of Ice B2 - Chest 1": FF1PRLocationData("Ice Region", "Treasure", 104),
    "Cavern of Ice B2 - Chest 2": FF1PRLocationData("Ice Region", "Treasure", 105),
    "Cavern of Ice B2 - Eye's Treasure": FF1PRLocationData("Ice Region", "GameObject", 254),
    "Cavern of Ice B3 - Ice Dragon Room 1": FF1PRLocationData("Ice Region", "Treasure", 106),
    "Cavern of Ice B3 - Ice Dragon Room 2": FF1PRLocationData("Ice Region", "Treasure", 107),
    "Cavern of Ice B3 - Six-Pack 1": FF1PRLocationData("Ice Region", "Treasure", 108),
    "Cavern of Ice B3 - Six-Pack 2": FF1PRLocationData("Ice Region", "Treasure", 109),
    "Cavern of Ice B3 - Six-Pack 3": FF1PRLocationData("Ice Region", "Treasure", 110),
    "Cavern of Ice B3 - Six-Pack 4": FF1PRLocationData("Ice Region", "Treasure", 111),
    "Cavern of Ice B3 - Six-Pack 5": FF1PRLocationData("Ice Region", "Treasure", 112),
    "Cavern of Ice B3 - Six-Pack 6": FF1PRLocationData("Ice Region", "Treasure", 113),
    "Cavern of Ice B1 - Greed 1": FF1PRLocationData("Ice Region", "Treasure", 99),
    "Cavern of Ice B1 - Greed 2": FF1PRLocationData("Ice Region", "Treasure", 100),
    "Cavern of Ice B1 - Drop Room 1": FF1PRLocationData("Ice Region", "Treasure", 101),
    "Cavern of Ice B1 - Drop Room 2": FF1PRLocationData("Ice Region", "Treasure", 102),
    "Cavern of Ice B1 - Drop Room 3": FF1PRLocationData("Ice Region", "Treasure", 103),
    "Citadel of Trials 2F - Side Chest": FF1PRLocationData("Trials Region", "Treasure", 240),
    "Citadel of Trials 3F - Single": FF1PRLocationData("Trials Region", "Treasure", 210),
    "Citadel of Trials 3F - Three-Pack 1": FF1PRLocationData("Trials Region", "Treasure", 211),
    "Citadel of Trials 3F - Three-Pack 2": FF1PRLocationData("Trials Region", "Treasure", 212),
    "Citadel of Trials 3F - Three-Pack 3": FF1PRLocationData("Trials Region", "Treasure", 213),
    "Citadel of Trials 3F - Four-Pack 1": FF1PRLocationData("Trials Region", "Treasure", 214),
    "Citadel of Trials 3F - Four-Pack 2": FF1PRLocationData("Trials Region", "Treasure", 215),
    "Citadel of Trials 3F - Four-Pack 3": FF1PRLocationData("Trials Region", "Treasure", 216),
    "Citadel of Trials 3F - Four-Pack 4": FF1PRLocationData("Trials Region", "Treasure", 217),
    "Citadel of Trials 3F - Mouse Chest": FF1PRLocationData("Trials Region", "Treasure", 512),
    "Dragon Caves (Forest) - Entrance 1": FF1PRLocationData("Dragon Region", "Treasure", 224),
    "Dragon Caves (Forest) - Entrance 2": FF1PRLocationData("Dragon Region", "Treasure", 225),
    "Dragon Caves (Forest) - Entrance 3": FF1PRLocationData("Dragon Region", "Treasure", 226),
    "Dragon Caves (Forest) - West Room 1": FF1PRLocationData("Dragon Region", "Treasure", 227),
    "Dragon Caves (Forest) - West Room 2": FF1PRLocationData("Dragon Region", "Treasure", 228),
    "Dragon Caves (Forest) - West Room 3": FF1PRLocationData("Dragon Region", "Treasure", 229),
    "Dragon Caves (Forest) - West Room 4": FF1PRLocationData("Dragon Region", "Treasure", 230),
    "Dragon Caves (Marsh) - Chest 1": FF1PRLocationData("Dragon Region", "Treasure", 221),
    "Dragon Caves (Marsh) - Chest 2": FF1PRLocationData("Dragon Region", "Treasure", 222),
    "Dragon Caves (Marsh) - Chest 3": FF1PRLocationData("Dragon Region", "Treasure", 223),
    "Dragon Caves (Plains) - Entrance": FF1PRLocationData("Dragon Region", "Treasure", 218),
    "Dragon Caves (Plains) - Duo 1": FF1PRLocationData("Dragon Region", "Treasure", 219),
    "Dragon Caves (Plains) - Duooo 2": FF1PRLocationData("Dragon Region", "Treasure", 220),
    "Waterfall Caverns - Chest 1": FF1PRLocationData("Waterfall", "Treasure", 114),
    "Waterfall Caverns - Chest 2": FF1PRLocationData("Waterfall", "Treasure", 115),
    "Waterfall Caverns - Chest 3": FF1PRLocationData("Waterfall", "Treasure", 116),
    "Waterfall Caverns - Chest 4": FF1PRLocationData("Waterfall", "Treasure", 117),
    "Waterfall Caverns - Chest 5": FF1PRLocationData("Waterfall", "Treasure", 118),
    "Waterfall Caverns - Chest 6": FF1PRLocationData("Waterfall", "Treasure", 119),
    "Waterfall Caverns - CubeBot": FF1PRLocationData("Waterfall", "GameObject", 404),
    "Gaia - Fairy": FF1PRLocationData("Gaia", "GameObject", 403),
    "Sunken Shrine 3F (Split) - Kraken Side Chest": FF1PRLocationData("Sunken Shrine", "Treasure", 130),
    "Sunken Shrine 3F (Split) - Mermaids Side Chest": FF1PRLocationData("Sunken Shrine", "Treasure", 131),
    "Sunken Shrine 4F - TFC": FF1PRLocationData("Sunken Shrine", "Treasure", 134),
    "Sunken Shrine 4F - TFC North": FF1PRLocationData("Sunken Shrine", "Treasure", 135),
    "Sunken Shrine 4F - Side Corner": FF1PRLocationData("Sunken Shrine", "Treasure", 136),
    "Sunken Shrine 4F - First Greed": FF1PRLocationData("Sunken Shrine", "Treasure", 137),
    "Sunken Shrine 4F - Second Greed": FF1PRLocationData("Sunken Shrine", "Treasure", 138),
    "Sunken Shrine 5F - Passby": FF1PRLocationData("Sunken Shrine", "Treasure", 139),
    "Sunken Shrine 5F - Bubbles 1": FF1PRLocationData("Sunken Shrine", "Treasure", 140),
    "Sunken Shrine 5F - Bubbles 2": FF1PRLocationData("Sunken Shrine", "Treasure", 141),
    "Sunken Shrine 5F - Far Room 1": FF1PRLocationData("Sunken Shrine", "Treasure", 142),
    "Sunken Shrine 5F - Far Room 2": FF1PRLocationData("Sunken Shrine", "Treasure", 143),
    "Sunken Shrine 5F - Far Major": FF1PRLocationData("Sunken Shrine", "Treasure", 507),
    "Sunken Shrine 5F - Entrance 1": FF1PRLocationData("Sunken Shrine", "Treasure", 144),
    "Sunken Shrine 5F - Entrance 2": FF1PRLocationData("Sunken Shrine", "Treasure", 145),
    "Sunken Shrine 5F - Entrance 3": FF1PRLocationData("Sunken Shrine", "Treasure", 146),
    "Sunken Shrine 5F - Four-Corner 1": FF1PRLocationData("Sunken Shrine", "Treasure", 147),
    "Sunken Shrine 5F - Four-Corner 2": FF1PRLocationData("Sunken Shrine", "Treasure", 148),
    "Sunken Shrine 5F - Four-Corner 3": FF1PRLocationData("Sunken Shrine", "Treasure", 149),
    "Sunken Shrine 5F - Four-Corner 4": FF1PRLocationData("Sunken Shrine", "Treasure", 150),
    "Sunken Shrine 3F (Corridor) - Top Chest": FF1PRLocationData("Sunken Shrine", "Treasure", 132),
    "Sunken Shrine 3F (Corridor) - Bottom Chest": FF1PRLocationData("Sunken Shrine", "Treasure", 133),
    "Sunken Shrine 2F - Dengbait 1": FF1PRLocationData("Sunken Shrine", "Treasure", 120),
    "Sunken Shrine 2F - Dengbait 2": FF1PRLocationData("Sunken Shrine", "Treasure", 121),
    "Sunken Shrine 2F - Side Corner 1": FF1PRLocationData("Sunken Shrine", "Treasure", 122),
    "Sunken Shrine 2F - Side Corner 2": FF1PRLocationData("Sunken Shrine", "Treasure", 123),
    "Sunken Shrine 2F - Side Corner 3": FF1PRLocationData("Sunken Shrine", "Treasure", 124),
    "Sunken Shrine 2F - Exit": FF1PRLocationData("Sunken Shrine", "Treasure", 125),
    "Sunken Shrine 2F - Shark 1": FF1PRLocationData("Sunken Shrine", "Treasure", 126),
    "Sunken Shrine 2F - Shark 2": FF1PRLocationData("Sunken Shrine", "Treasure", 127),
    "Sunken Shrine 2F - Shark 3": FF1PRLocationData("Sunken Shrine", "Treasure", 128),
    "Sunken Shrine 2F - Shark 4": FF1PRLocationData("Sunken Shrine", "Treasure", 129),
    "Lufenia - Lufenian Man": FF1PRLocationData("Lufenia Region", "GameObject", 255),
    "Mirage Tower 1F - Chest 1": FF1PRLocationData("Mirage Tower", "Treasure", 151),
    "Mirage Tower 1F - Chest 2": FF1PRLocationData("Mirage Tower", "Treasure", 152),
    "Mirage Tower 1F - Chest 3": FF1PRLocationData("Mirage Tower", "Treasure", 153),
    "Mirage Tower 1F - Chest 4": FF1PRLocationData("Mirage Tower", "Treasure", 154),
    "Mirage Tower 1F - Chest 5": FF1PRLocationData("Mirage Tower", "Treasure", 155),
    "Mirage Tower 1F - Chest 6": FF1PRLocationData("Mirage Tower", "Treasure", 156),
    "Mirage Tower 1F - Chest 7": FF1PRLocationData("Mirage Tower", "Treasure", 157),
    "Mirage Tower 1F - Chest 8": FF1PRLocationData("Mirage Tower", "Treasure", 158),
    "Mirage Tower 2F - Lesser 1": FF1PRLocationData("Mirage Tower", "Treasure", 159),
    "Mirage Tower 2F - Lesser 2": FF1PRLocationData("Mirage Tower", "Treasure", 160),
    "Mirage Tower 2F - Lesser 3": FF1PRLocationData("Mirage Tower", "Treasure", 161),
    "Mirage Tower 2F - Lesser 4": FF1PRLocationData("Mirage Tower", "Treasure", 162),
    "Mirage Tower 2F - Lesser 5": FF1PRLocationData("Mirage Tower", "Treasure", 163),
    "Mirage Tower 2F - Greater 1": FF1PRLocationData("Mirage Tower", "Treasure", 164),
    "Mirage Tower 2F - Greater 2": FF1PRLocationData("Mirage Tower", "Treasure", 165),
    "Mirage Tower 2F - Greater 3": FF1PRLocationData("Mirage Tower", "Treasure", 166),
    "Mirage Tower 2F - Greater 4": FF1PRLocationData("Mirage Tower", "Treasure", 167),
    "Mirage Tower 2F - Greater 5": FF1PRLocationData("Mirage Tower", "Treasure", 168),
    "Flying Fortress 1F - Solo": FF1PRLocationData("Flying Fortress", "Treasure", 178),
    "Flying Fortress 1F - West Room 1": FF1PRLocationData("Flying Fortress", "Treasure", 169),
    "Flying Fortress 1F - West Room 2": FF1PRLocationData("Flying Fortress", "Treasure", 170),
    "Flying Fortress 1F - West Room 3": FF1PRLocationData("Flying Fortress", "Treasure", 171),
    "Flying Fortress 1F - West Room 4": FF1PRLocationData("Flying Fortress", "Treasure", 172),
    "Flying Fortress 1F - East Room 1": FF1PRLocationData("Flying Fortress", "Treasure", 173),
    "Flying Fortress 1F - East Room 2": FF1PRLocationData("Flying Fortress", "Treasure", 174),
    "Flying Fortress 1F - East Room 3": FF1PRLocationData("Flying Fortress", "Treasure", 175),
    "Flying Fortress 1F - East Room 4": FF1PRLocationData("Flying Fortress", "Treasure", 176),
    "Flying Fortress 1F - East Room 5": FF1PRLocationData("Flying Fortress", "Treasure", 177),
    "Flying Fortress 2F - Cheap Room 1": FF1PRLocationData("Flying Fortress", "Treasure", 179),
    "Flying Fortress 2F - Cheap Room 2": FF1PRLocationData("Flying Fortress", "Treasure", 180),
    "Flying Fortress 2F - Vault 1": FF1PRLocationData("Flying Fortress", "Treasure", 181),
    "Flying Fortress 2F - Vault 2": FF1PRLocationData("Flying Fortress", "Treasure", 182),
    "Flying Fortress 2F - Major": FF1PRLocationData("Flying Fortress", "Treasure", 250),
    "Flying Fortress 2F - Gauntlet Room": FF1PRLocationData("Flying Fortress", "Treasure", 183),
    "Flying Fortress 2F - Ribbon Room 1": FF1PRLocationData("Flying Fortress", "Treasure", 184),
    "Flying Fortress 2F - Ribbon Room 2": FF1PRLocationData("Flying Fortress", "Treasure", 185),
    "Flying Fortress 2F - Wardrobe 1": FF1PRLocationData("Flying Fortress", "Treasure", 186),
    "Flying Fortress 2F - Wardrobe 2": FF1PRLocationData("Flying Fortress", "Treasure", 187),
    "Flying Fortress 3F - CC's Gambit 1": FF1PRLocationData("Flying Fortress", "Treasure", 188),
    "Flying Fortress 3F - CC's Gambit 2": FF1PRLocationData("Flying Fortress", "Treasure", 189),
    "Flying Fortress 3F - CC's Gambit 3": FF1PRLocationData("Flying Fortress", "Treasure", 190),
    "Flying Fortress 3F - CC's Gambit 4": FF1PRLocationData("Flying Fortress", "Treasure", 191),
    "Flying Fortress 3F - Six-Pack 1": FF1PRLocationData("Flying Fortress", "Treasure", 192),
    "Flying Fortress 3F - Six-Pack 2": FF1PRLocationData("Flying Fortress", "Treasure", 193),
    "Flying Fortress 3F - Six-Pack 3": FF1PRLocationData("Flying Fortress", "Treasure", 194),
    "Flying Fortress 3F - Six-Pack 4": FF1PRLocationData("Flying Fortress", "Treasure", 195),
    "Flying Fortress 3F - Six-Pack 5": FF1PRLocationData("Flying Fortress", "Treasure", 196),
    "Flying Fortress 3F - Six-Pack 6": FF1PRLocationData("Flying Fortress", "Treasure", 197),
    "Flying Fortress 3F - Exit 1": FF1PRLocationData("Flying Fortress", "Treasure", 198),
    "Flying Fortress 3F - Exit 2": FF1PRLocationData("Flying Fortress", "Treasure", 199),
    "Flying Fortress 3F - Exit 3": FF1PRLocationData("Flying Fortress", "Treasure", 200),
    "Flying Fortress 3F - Exit 4": FF1PRLocationData("Flying Fortress", "Treasure", 201),
    "Chaos Shrine 3F - Validation 1": FF1PRLocationData("Beyond the Black Orb", "Treasure", 202),
    "Chaos Shrine 3F - Validation 2": FF1PRLocationData("Beyond the Black Orb", "Treasure", 203),
    "Chaos Shrine B2 (Fire) - Right Chest": FF1PRLocationData("Beyond the Black Orb", "Treasure", 204),
    "Chaos Shrine B2 (Fire) - Left Chest": FF1PRLocationData("Beyond the Black Orb", "Treasure", 205),
    "Chaos Shrine B2 (Fire) - Eastern Vault": FF1PRLocationData("Beyond the Black Orb", "Treasure", 206),
    "Chaos Shrine B2 (Fire) - Southern Vault": FF1PRLocationData("Beyond the Black Orb", "Treasure", 207),
    "Chaos Shrine B4 (Air) - Legendary Chest": FF1PRLocationData("Beyond the Black Orb", "Treasure", 208),
}

event_table: Dict[str, FF1PRLocationData] = {
    "Chaos Shrine - Garland": FF1PRLocationData("Pravoka Region", "Event", 0),
    "Mount Duergar - Nerrick": FF1PRLocationData("Innersea Region", "Event", 0),
    "Cavern of Earth - Vampire": FF1PRLocationData("Melmond Region", "Event", 0),
    "Giant's Cave - Titan": FF1PRLocationData("Melmond Region", "Event", 0),
    "Cavern of Earth - Lich": FF1PRLocationData("Cavern of Earth Deep", "Event", 0),
    "Ryukhan Desert - Airship": FF1PRLocationData("Ryukhan Desert", "Event", 0),
    "Mount Gulg - Kary": FF1PRLocationData("Gulg Region", "Event", 0),
    "Caravan": FF1PRLocationData("Onrac Region", "Event", 0),
    "Onrac - Sub Engineer": FF1PRLocationData("Onrac Region", "Event", 0),
    "Sunken Shrine - Kraken": FF1PRLocationData("Sunken Shrine", "Event", 0),
    "Melmond - Dr Unne": FF1PRLocationData("Melmond Region", "Event", 0),
    "Flying Fortress - Tiamat": FF1PRLocationData("Flying Fortress", "Event", 0),
    "Chaos Shrine - Black Orb": FF1PRLocationData("Pravoka Region", "Event", 0),
    "Chaos Shrine - Chaos": FF1PRLocationData("Beyond the Black Orb", "Event", 0),
}


standard_location_name_to_id: Dict[str, int] = {name: location_base_id + index for index, name in enumerate(location_table)}

all_locations = location_table.copy()

location_name_groups: Dict[str, Set[str]] = {}
for loc_name, loc_data in location_table.items():
    loc_group_name = loc_name.split(" - ", 1)[0]
    location_name_groups.setdefault(loc_group_name, set()).add(loc_name)